#! /bin/bash

cat > math.e <<EOT
(((2+3)-1)*3)/2;
EOT

python compiler.py < math.e > math.lmc
python assembler.py math.lmc math.dec
python disassembler.py math.dec math.dis
python simulator.py math.dec > math.run
cat math.run

