#! /bin/bash

echo ---- assemble/disassemble test.lmc

python assembler.py test.lmc test.out
python disassembler.py test.out test.dis

echo ---- assemble/disassemble multiply.lmc

python assembler.py multiply.lmc multiply.out
python disassembler.py multiply.out multiply.dis

echo ---- simulate multiply.lmc

python simulator.py multiply.out <<EOT > multiply.run
5
3
EOT

echo ---- interactive session to add two numbers

python interactive.py <<EOT > interactive.run
INP
10
STA 010
INP
20
STA 011
LDA 010
ADD 011
STA 012
LDA 012
OUT
HLT
EOT

